import os

# os.system('./run.sh SSM/attn/256K/ > SSM/attn/256K/log.txt')
# os.system('./run.sh SSM/attn/512K/ > SSM/attn/512K/log.txt')
# os.system('./run.sh SSM/attn/1M/ > SSM/attn/1M/log.txt')
# os.system('./run.sh SSM/Hyena/gemm_fft/256K_A100/ > SSM/Hyena/gemm_fft/256K_A100/log.txt')
# os.system('./run.sh SSM/Hyena/gemm_fft/256K_SN40L/ > SSM/Hyena/gemm_fft/256K_SN40L/log.txt')
# os.system('./run.sh SSM/Hyena/gemm_fft/256K_VGA/ > SSM/Hyena/gemm_fft/256K_VGA/log.txt')
# os.system('./run.sh SSM/Hyena/gemm_fft/512K_A100/ > SSM/Hyena/gemm_fft/512K_A100/log.txt')
# os.system('./run.sh SSM/Hyena/gemm_fft/512K_SN40L/ > SSM/Hyena/gemm_fft/512K_SN40L/log.txt')
# os.system('./run.sh SSM/Hyena/gemm_fft/512K_VGA/ > SSM/Hyena/gemm_fft/512K_VGA/log.txt')
# os.system('./run.sh SSM/Hyena/gemm_fft/1M_A100/ > SSM/Hyena/gemm_fft/1M_A100/log.txt')
# os.system('./run.sh SSM/Hyena/gemm_fft/1M_SN40L/ > SSM/Hyena/gemm_fft/1M_SN40L/log.txt')
# os.system('./run.sh SSM/Hyena/gemm_fft/1M_VGA/ > SSM/Hyena/gemm_fft/1M_VGA/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft/256K_SN40L/ > SSM/Hyena/vector_fft/256K_SN40L/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft/512K_SN40L/ > SSM/Hyena/vector_fft/512K_SN40L/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft/1M_SN40L/ > SSM/Hyena/vector_fft/1M_SN40L/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft_wo_hw/256K_SN40L/ > SSM/Hyena/vector_fft_wo_hw/256K_SN40L/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft_wo_hw/256K_VGA/ > SSM/Hyena/vector_fft_wo_hw/256K_VGA/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft_wo_hw/256K_A100_cuda/ > SSM/Hyena/vector_fft_wo_hw/256K_A100_cuda/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft_wo_hw/256K_A100_tensor/ > SSM/Hyena/vector_fft_wo_hw/256K_A100_tensor/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft_wo_hw/512K_SN40L/ > SSM/Hyena/vector_fft_wo_hw/512K_SN40L/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft_wo_hw/512K_VGA/ > SSM/Hyena/vector_fft_wo_hw/512K_VGA/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft_wo_hw/512K_A100_cuda/ > SSM/Hyena/vector_fft_wo_hw/512K_A100_cuda/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft_wo_hw/512K_A100_tensor/ > SSM/Hyena/vector_fft_wo_hw/512K_A100_tensor/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft_wo_hw/1M_SN40L/ > SSM/Hyena/vector_fft_wo_hw/1M_SN40L/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft_wo_hw/1M_VGA/ > SSM/Hyena/vector_fft_wo_hw/1M_VGA/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft_wo_hw/1M_A100_cuda/ > SSM/Hyena/vector_fft_wo_hw/1M_A100_cuda/log.txt')
# os.system('./run.sh SSM/Hyena/vector_fft_wo_hw/1M_A100_tensor/ > SSM/Hyena/vector_fft_wo_hw/1M_A100_tensor/log.txt')
# os.system('./run.sh SSM/Mamba/serialscan/256K_RDU/ > SSM/Mamba/serialscan/256K_RDU/log.txt')
# os.system('./run.sh SSM/Mamba/serialscan/512K_RDU/ > SSM/Mamba/serialscan/512K_RDU/log.txt')
# os.system('./run.sh SSM/Mamba/serialscan/1M_RDU/ > SSM/Mamba/serialscan/1M_RDU/log.txt')

# os.system('./run.sh SSM/Mamba/parallelscan_wo_hw/256K_RDU/ > SSM/Mamba/parallelscan_wo_hw/256K_RDU/log.txt')
# os.system('./run.sh SSM/Mamba/parallelscan_wo_hw/256K_A100_cuda/ > SSM/Mamba/parallelscan_wo_hw/256K_A100_cuda/log.txt')
# os.system('./run.sh SSM/Mamba/parallelscan_wo_hw/256K_A100_tensor/ > SSM/Mamba/parallelscan_wo_hw/256K_A100_tensor/log.txt')
# os.system('./run.sh SSM/Mamba/parallelscan_wo_hw/512K_RDU/ > SSM/Mamba/parallelscan_wo_hw/512K_RDU/log.txt')
# os.system('./run.sh SSM/Mamba/parallelscan_wo_hw/512K_A100_cuda/ > SSM/Mamba/parallelscan_wo_hw/512K_A100_cuda/log.txt')
# os.system('./run.sh SSM/Mamba/parallelscan_wo_hw/512K_A100_tensor/ > SSM/Mamba/parallelscan_wo_hw/512K_A100_tensor/log.txt')
# os.system('./run.sh SSM/Mamba/parallelscan_wo_hw/1M_RDU/ > SSM/Mamba/parallelscan_wo_hw/1M_RDU/log.txt')
# os.system('./run.sh SSM/Mamba/parallelscan_wo_hw/1M_A100_cuda/ > SSM/Mamba/parallelscan_wo_hw/1M_A100_cuda/log.txt')
# os.system('./run.sh SSM/Mamba/parallelscan_wo_hw/1M_A100_tensor/ > SSM/Mamba/parallelscan_wo_hw/1M_A100_tensor/log.txt')


os.system('./run.sh SSM/Mamba/bscan_w_hw/256K_RDU/ > SSM/Mamba/bscan_w_hw/256K_RDU/log.txt')
os.system('./run.sh SSM/Mamba/bscan_w_hw/512K_RDU/ > SSM/Mamba/bscan_w_hw/512K_RDU/log.txt')
os.system('./run.sh SSM/Mamba/bscan_w_hw/1M_RDU/ > SSM/Mamba/bscan_w_hw/1M_RDU/log.txt')
os.system('./run.sh SSM/Mamba/hsscan_w_hw/256K_RDU/ > SSM/Mamba/hsscan_w_hw/256K_RDU/log.txt')
os.system('./run.sh SSM/Mamba/hsscan_w_hw/512K_RDU/ > SSM/Mamba/hsscan_w_hw/512K_RDU/log.txt')
os.system('./run.sh SSM/Mamba/hsscan_w_hw/1M_RDU/ > SSM/Mamba/hsscan_w_hw/1M_RDU/log.txt')

